# Generated by Django 5.1.3 on 2024-11-11 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='email',
            field=models.TextField(default='temp_email@example.com', unique=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='password',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.TextField(default='testname', unique=True),
        ),
    ]
